env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: 2019-nConv-risk
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - amd64
      - arm
      - arm64
archives:
  - id: tar
    format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip