env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: 2019-nConv-risk
    goos:
      - freebsd
      - windows
    goarm:
      - amd64
      - arm
      - arm64
archives:
  - id: tar
    format: tar.gz
    replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip